language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libbluetooth-dev libusb-1.0-0-dev libgudev-1.0-dev unixodbc-dev libdbi-dev libdbd-sqlite3
  - sudo pip install cpp-coveralls --use-mirrors
script:
  - mkdir build && cd build && cmake .. -DCMAKE_C_COMPILER=$CC -DCOVERAGE=ON && make && make test
after_success:
  - coveralls
