language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libbluetooth-dev libusb-1.0-0-dev libgudev-1.0-dev unixodbc-dev libdbi-dev libdbd-sqlite3
script:
  - mkdir build && cd build && cmake .. -DCMAKE_C_COMPILER=$CC -DCOVERAGE=ON -DCMAKE_BUILD_TYPE=Continuous && make && make test
after_success:
  - ./coveralls-upload
addons:
  coverity_scan:
    project:
      name: "gammu/gammu"
      description: "Build submitted via Travis CI"
    notification_email: michal@cihar.com
    build_command_prepend: "mkdir coverity && cd coverity && cmake .."
    build_command: "cd coverity && make"
    branch_pattern: master
