os:
  - linux
language: cpp
compiler:
  - gcc
env:
  matrix:
    - ARGS=""
  global:
    - CTEST_OUTPUT_ON_FAILURE=1
    - TESTARGS="-DMYSQL_TESTING=on -DPSQL_TESTING=ON -DMYSQL_USER=root -DPSQL_USER=postgres -DPSQL_PASSWORD= -DODBC_TESTING=ON -DODBC_DSN=ODBCTest" 
before_script:
  - mkdir _build
  - cd _build
script:
  - echo
after_failure:
  - if [ -f cov-int/build-log.txt ] ; then cat cov-int/build-log.txt ; fi
# trigger Buildtime Trend Service to parse Travis CI log
notifications:
  webhooks:
    - https://buildtimetrend.herokuapp.com/travis
# use docker based faster build
sudo: false
# install build dependencies and enable Coverity scan
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
    - libbluetooth-dev
    - libusb-1.0-0-dev
    - libgudev-1.0-dev
    - unixodbc-dev
    - libdbi-dev
    - libdbd-sqlite3
    - libdbd-mysql
    - libdbd-pgsql
    - cmake
    - cmake-data
    - libmyodbc
  coverity_scan:
    project:
      name: "gammu/gammu"
      description: "Build submitted via Travis CI"
    notification_email: michal@cihar.com
    build_command_prepend: cmake ..
    build_command: make
    branch_pattern: coverity_scan
