language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libbluetooth-dev libusb-1.0-0-dev libgudev-1.0-dev unixodbc-dev libdbi-dev libdbd-sqlite3
before_script:
  - mkdir _build
  - cd _build
script:
  - cmake .. -DCMAKE_C_COMPILER=$CC -DCOVERAGE=ON -DCMAKE_BUILD_TYPE=Continuous
  - make
  - make test
after_success:
  - ../coveralls-upload
addons:
  coverity_scan:
    project:
      name: "gammu/gammu"
      description: "Build submitted via Travis CI"
    notification_email: michal@cihar.com
    build_command_prepend: "cmake .."
    build_command: "make"
    branch_pattern: coverity_scan
