version: {build}

environment:
  matrix:
    - GENERATOR: "Visual Studio 14"
    - GENERATOR: "Visual Studio 14 Win64"

clone_folder: c:\projects\gammu

before_build:
- cmd: >-
    cd c:\projects\gammu
    cmake -G "%GENERATOR%" -DCMAKE_INSTALL_PREFIX=%P%

build:
  project: ALL_BUILD.vcxproj
  parallel: true
  verbosity: minimal

#test_script:
#  - ps: cd _builds
#  - ctest -VV -C "%CONFIG%"
