version: "{build}"

configuration: Release

shallow_clone: true

environment:
  MYSQL_PATH: C:\Program Files\MySql\MySQL Server 5.7
  matrix:
    - GENERATOR: "Visual Studio 14"
    - GENERATOR: "Visual Studio 14 Win64"

clone_folder: c:\projects\gammu

install:
  - "SET PATH=%MYSQL_PATH%\\bin;%PATH%"
  - wget https://download.microsoft.com/download/f/2/6/f263ac46-1fe9-4ae9-8fd3-21102100ebf5/msxsl.exe

before_build:
  - mysql "--password=Password12!" --user=root -e "create database smsd;"
  - cmake -G "%GENERATOR%" -DCMAKE_INSTALL_PREFIX=%P% -DODBC_DSN=mysql:host=localhost;dbname=smsd -DMYSQL_USER=root "-DMYSQL_PASSWORD=Password12!" -DODBC_TESTING=ON "-DMYSQL_ADD_INCLUDE_DIR=%MYSQL_PATH%\\include" "-DMYSQL_ADD_LIBRARY_PATH=%MYSQL_PATH%\\lib"

build:
  project: ALL_BUILD.vcxproj
  parallel: true
  verbosity: minimal

after_build:
  - cmake --build .  --config Release --target package

test_script:
  - ps: >-
        Try 
        {
            ctest --output-on-failure --no-compress-output --dashboard ExperimentalTest --build-config Release
        }
        Finally
        {
            Copy-Item Testing\$(Get-Content Testing\TAG -TotalCount 1)\Test.xml test.xml
            msxsl test.xml admin/ctest-to-junit.xsl -o junit.xml
            # upload results to AppVeyor
            $wc = New-Object 'System.Net.WebClient'
            $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\junit.xml))
        }

services:
  - mysql

artifacts:
  - path: Gammu-*-Windows.exe
    name: Installer
