version: "{build}"

environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  matrix:
    - GENERATOR: "Visual Studio 14"
    - GENERATOR: "Visual Studio 14 Win64"

clone_folder: c:\projects\gammu

before_build:
  - cd c:\projects\gammu
  - cmake -G "%GENERATOR%" -DCMAKE_INSTALL_PREFIX=%P%

build:
  project: ALL_BUILD.vcxproj
  parallel: true
  verbosity: minimal

test_script:
  - msbuild RUN_TESTS.vcxproj
