version: "{build}"

shallow_clone: true

environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  MYSQL_PATH: C:\Program Files\MySql\MySQL Server 5.7
  matrix:
    - GENERATOR: "Visual Studio 14"
    - GENERATOR: "Visual Studio 14 Win64"

clone_folder: c:\projects\gammu

install:
  - "SET PATH=%MYSQL_PATH%\\bin;%PATH%"

before_build:
  - mysql "--password=Password12!" --user=root -e "create database smsd;"
  - cmake -G "%GENERATOR%" -DCMAKE_INSTALL_PREFIX=%P% -DODBC_DSN=mysql:host=localhost;dbname=smsd -DMYSQL_USER=root "-DMYSQL_PASSWORD=Password12!" -DODBC_TESTING=ON -DMYSQL_ADD_INCLUDE_DIR=%MYSQL_PATH%\include -DMYSQL_ADD_LIBRARY_PATH=%MYSQL_PATH%\lib

build:
  project: ALL_BUILD.vcxproj
  parallel: true
  verbosity: minimal

after_build:
  - cmake --build . --target package

test_script:
  - msbuild RUN_TESTS.vcxproj

services:
  - mysql
