version: "{build}"

shallow_clone: true

environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  matrix:
    - GENERATOR: "Visual Studio 14"
    - GENERATOR: "Visual Studio 14 Win64"

clone_folder: c:\projects\gammu

before_build:
  - cd c:\projects\gammu
  - "C:\Program Files\MySql\MySQL Server 5.7\bin\mysql" "--password=Password12!" --user=root -e "create database smsd;"
  - cmake -G "%GENERATOR%" -DCMAKE_INSTALL_PREFIX=%P% -DODBC_DSN=mysql:host=localhost;dbname=smsd -DMYSQL_USER=root "-DMYSQL_PASSWORD=Password12!"

build:
  project: ALL_BUILD.vcxproj
  parallel: true
  verbosity: minimal

test_script:
  - msbuild RUN_TESTS.vcxproj

services:
  - mysql
